# КУХНЯ. УПРАВЛЕНИЕ КАНАЛОМ 1
- alias: kitchen_2x_switch_1
  #initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0006d31880_action
      to: 'left'
  action:
    - service: switch.toggle
      entity_id: switch.0x00158d00067c97ef_l1

# КУХНЯ. УПРАВЛЕНИЕ КАНАЛОМ 2
- alias: kitchen_2x_switch_2
  #initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0006d31880_action
      to: 'right'
  action:
    - service: switch.toggle
      entity_id: switch.0x00158d00067c97ef_l2

# КУХНЯ. ВЫКЛЮЧИТЬ ВСЁ
- alias: kitchen_2x_switch_all
  #initial_state: false
  trigger:
    - platform: state
      entity_id: sensor.0x00158d0006d31880_action
      to: 'right_long'
  action:
    - service: switch.turn_off
      entity_id:
      - switch.0x00158d00067c97ef_l1
      - switch.0x00158d00067c97ef_l2